- alert: NginxServiceDown
  expr: node_systemd_unit_state{exported_name="nginx.service", state="active"} < 1
  for: 2m
  labels:
    severity: critical
  annotations:
    summary: Nginx Service Down
- alert: BackendServiceDown
  expr: node_systemd_unit_state{exported_name="backend.service", state="active"} < 1
  for: 2m
  labels:
    severity: critical
  annotations:
    summary: Backend Service Down
- name: SaturationAlerts
  rules:
    - alert: MemoryUsedPercentageWarning
      expr: (1- ((node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes)) * 100 > 80
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: Memory Used Percentage in Warning State
    - alert: MemoryUsedPercentageCritical
      expr: (1- ((node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes)) * 100 > 90
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: Memory Used Percentage in Critical State
    - alert: CPUUsageWarning
      expr: avg by (instance) ((1 - (rate(node_cpu_seconds_total{mode="idle"}[5m]))) * 100) > 80
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: CPU Usage in Warning State
    - alert: MemoryUsageCritical
      expr: avg by (instance) ((1 - (rate(node_cpu_seconds_total{mode="idle"}[5m]))) * 100) > 90
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: CPU Usage in Critical State
    - alert: NetworkPacketQueueOrDropCount
      expr: increase(node_ethtool_pps_allowance_exceeded[5m]) > 1
      for: 10m
      labels:
        severity: critical
      annotations:
        summary: Network packets Queued / Dropped