- name: Download prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    dest: /opt
    remote_src: true

- name: Copy Prometheus service file
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: Start prometheus service
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Copy Prometheus Server configuration
  ansible.builtin.template:
    src: jenkins.repos
    dest: /opt/prometheus-{{ prometheus_version }}.linux-amd64/jenkins.repos

- name: Copy Prometheus Alerts configuration
  ansible.builtin.template:
    src: alerts.yml
    dest: /opt/prometheus-{{ prometheus_version }}.linux-amd64/alerts.yml

