format_version: 10
pipelines:
  jenkins-ansible:
    group: tools
    label_template: "${COUNT}"
    materials:
      ansible:
        git: https://github.com/jedlinks/miscellaneous-code
        shallow_clone: false
        auto_update: false
        branch: main
        includes:
          - src/**/*.*
    stages:
      - apply:
          fetch_materials: true
          jobs:
            apply:
              approval:
                type: manual
              timeout: 0
              tasks:
                - exec:
                    working_directory: prometheus
                    command: bash
                    arguments: [ "ansible.sh", "jenkins" ]