format_version: 10
pipelines:
  prometheus-terraform:
    group: tools
    label_template: "${COUNT}"
    materials:
      ansible:
        git: https://github.com/jedlinks/miscellaneous-code
        shallow_clone: false
        auto_update: false
        branch: main
    stages:
      - apply:
          fetch_materials: true
          jobs:
            apply:
              approval:
                type: auto
              timeout: 0
              tasks:
                - exec:
                    command: terraform
                    arguments: ["init"]
                    working_directory: prometheus

                - exec:
                    command: terraform
                    arguments: ["apply", "-auto-approve"]
                    working_directory: prometheus